# based on https://github.com/pyinstaller/pyinstaller/issues/6296#issuecomment-943620645
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version: 3.13.12
        
    - name: Install Dependencies and PyInstaller
      run: pip install -r requirements.txt pyinstaller
      
    - name: Package Files
      run: pyinstaller main.spec

    - name: Zip Files
      run: Compress-Archive -Path dist/pyauto-runner -DestinationPath pyauto-runner.zip
      shell: pwsh
      
    - name: Release Zip
      uses: softprops/action-gh-release@v1
      with:
        files: |
          pyauto-runner.zip
